version: '2.1'
services:
  url-shortener:
    image: url-shortener:1.1
    ports:
      - 8081:8081
    depends_on:
       mysql:
        condition: service_healthy
  mysql:
    image: mysql:8.0.32-debian
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 5s
            retries: 10
  