version: '1'
services:
  url-shortener:
    image: url-shortener:1.0
    ports:
      - 8081:8081
  mysql:
    image: mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root